version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    volumes:
      - ./get_data/backups:/app/get_data/backups
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: research_papers
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
volumes:
  db_data:
networks:
  app-network:
    driver: bridge